# Generated by Django 4.2.1 on 2024-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volleyball',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='volleyball',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='volleyball',
            index=models.Index(fields=['-time_create'], name='volleyball__time_cr_c36cd6_idx'),
        ),
    ]
