# Generated by Django 4.2.1 on 2024-11-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0003_alter_volleyball_slug_alter_volleyball_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volleyball',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Не существует'), (1, 'Существует')], default=0),
        ),
        migrations.AlterField(
            model_name='volleyball',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
