# Generated by Django 4.2.1 on 2024-11-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0005_category_volleyball_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volleyball',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volleyball.category'),
        ),
    ]
