# Generated by Django 4.2.1 on 2024-11-24 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0006_alter_volleyball_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='volleyball',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volleyball.category'),
        ),
        migrations.AddField(
            model_name='volleyball',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='volleyball.tagteam'),
        ),
    ]
